### ISSUE TITLE
Run end-to-end tests in atomic-server CI 

### ISSUE THREAD

**Issue by joepio** [joepio/atomic-data-rust#204]
Although the e2e tests are run in the `atomic-data-browser` CI, they are not being run here. This has previously led to broken docker builds before - and that harms the developer experience.

I think it would be not that hard to run the e2e tests here.

Options:

## Dockerize e2e tests, load docker image

- Requires publishing yet another docker image

## Git pull e2e tests, run yarn

- Will probably be pretty slow

**Comment by joepio** [comment]
Now that I've got #185 pretty much done, I think this is more manageable. 

Still not sure what the best way forward is. 

This is how the e2e are executed in `atomic-data-browser`:

```yml
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: bahmutov/npm-install@v1
      - run: npx playwright install-deps
      - run: yarn test

```

This means we need to run `yarn`, which means a `package.json`, and the tests themselves of course.

Seems a bit much. Is there a simpler way, maybe?

yes! There is `npx playwright test tests/todo-page.spec.ts`, which for some reason seems to take ages to run on my laptop. Bu anyway, that would remove the need for a `package.json`.

Getting the test file itself is still a matter of copy/paste, which will
